# -*- coding: utf-8 -*-
"""PPLM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux0Z4-ruiVtJ6jUk98uk6FqfvGHCOYL3

# Setup
"""

#!git clone https://github.com/uber-research/PPLM.git

import os
os.chdir('PPLM')

#!pip install -r requirements.txt

from transformers import GPT2LMHeadModel
# This downloads GPT-2 Medium, it takes a little while
_ = GPT2LMHeadModel.from_pretrained("gpt2-medium")

from run_pplm import run_pplm_example

"""# Let's generate some text!
When you specify a number of samples, PPLM will first generate a sample without any modification for reference (called "unperturbed"), and then the number of samples specified (called "perturbed"). If you want to generate different samples given the same parameters, change the `seed` value to a number other than 0 (the default value).
"""

run_pplm_example(
    cond_text="The potato",
    num_samples=3,
    bag_of_words='military',
    length=50,
    stepsize=0.03,
    sample=True,
    num_iterations=3,
    window_length=5,
    gamma=1.5,
    gm_scale=0.95,
    kl_scale=0.01,
    verbosity='regular'
)

run_pplm_example(
    cond_text="My dog died",
    num_samples=3,
    discrim='sentiment',
    class_label='very_positive',
    length=50,
    stepsize=0.05,
    sample=True,
    num_iterations=10,
    gamma=1,
    gm_scale=0.9,
    kl_scale=0.02,
    verbosity='regular'
)